# Generated by Django 5.2.3 on 2025-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_letters",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="job_analyzed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="resume_analyzed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="success_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
